# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0003_auto_20180413_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boundaries.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='label',
            field=models.CharField(default='Cidade', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='label',
            field=models.CharField(default='Estado', max_length=255),
            preserve_default=False,
        ),
    ]
