# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0004_auto_20180501_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='acronym',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
